name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '* * * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup git
      run: (git config --global user.email "you@example.com" && git config --global user.name "Your Name")

    - name: Install dependencies
      run: yarn --frozen--lockfile

    - name: Run tests
      run: yarn test
